PFA-Project/Models/Famille.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.Drawing;

namespace PFA_Project.Models
{
    public class Famille
    {
        public int Id { get; set; }
        public string ?Libelle { get; set; }
         public string ?Couleur{ get; set; }
        public List<Produit> ?produits { get; set; }
    }
}

PFA-Project/Controllers/FamilleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PFA_Project.Filters;
using PFA_Project.Models;
using System.Drawing;

namespace PFA_Project.Controllers
{
    [AuthFilter("Admin")]
    public class FamilleController : Controller
    {
        public ApplicationContext db;

        public FamilleController(ApplicationContext db)
        {
            this.db = db;
        }
        public IActionResult List()
        {
            List<Famille> familles = db.Familles.ToList();
            return View(familles);
        }
        public IActionResult Ajouter()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Ajouter(Famille famille)
        {
            if (ModelState.IsValid)
            {
                //ayakhod le type hexadecimal o k anffectewha lcouleur
              //  string hex = famille.Couleur.R.ToString("X2") + famille.Couleur.G.ToString("X2") + famille.Couleur.B.ToString("X2");
               // famille.Couleur = hex;
                db.Familles.Add(famille);
                db.SaveChanges();
                return RedirectToAction("List");
            }
            return View(famille);
        }
        public IActionResult Modifier(int ?id)
        {
        if (id == null)
        {
            return RedirectToAction("List");
        }
        var fa = db.Familles.Find(id);
        if (fa == null)
        {
            return RedirectToAction("List");
        }
        return View(fa);
    }
        [HttpPost]
        public IActionResult Modifier(Famille famille)
        {
            if (ModelState.IsValid)
            {
                //string hex = famille.Couleur1.R.ToString("X2") + famille.Couleur1.G.ToString("X2") + famille.Couleur1.B.ToString("X2");
               // famille.Couleur = hex;
                db.Update(famille);
                db.SaveChanges();
                return RedirectToAction("List");
            }
            return View(famille);
       
        }
        public IActionResult Supprimer(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("List");
            }
            var famille = db.Familles.Find(id);
            if (famille != null)
            {
                db.Familles.Remove(famille);
                db.SaveChanges();
                return RedirectToAction("List");
            }
            return RedirectToAction("List");
        }
    }
}

PFA-Project/Views/Famille/Ajouter.cshtml
@model Famille

<div class="page-header">
    <h3 class="page-title">Ajouter  des familles</h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/Famille/List">Retourner vers la liste</a></li>

        </ol>
    </nav>
</div>
<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">

                <p>
                    <a class="btn btn-primary btn-rounded btn-icon" asp-action="Ajouter" asp-controller="Famille">
                        <i class="mdi mdi-tag-multiple"></i>
                    </a>
                </p>
                <form class="forms-sample" method="post">
                    <div asp-validation-summary="All" />
                    <div class="form-group">
                        <label for="ref">Libellé</label>
                        <input type="text" class="form-control" asp-for="Libelle" placeholder="Libellé" />
                        <span asp-validation-for="Libelle"></span>
                    </div>
                    <div class="form-group">
                        <label for="couleur">Couleur</label>
                        <input type="color" class="form-control" asp-for="Couleur" placeholder="Couleur" />
                        <span asp-validation-for="Couleur"></span>
                    </div>
                   
                    <div class="template-demo mt-2">
                        <button type="submit" class="btn btn-primary btn-rounded btn-fw"> Ajouter Famille</button>

                    </div>
                </form>

            </div>
        </div>
    </div>
</div>

PFA-Project/Views/Famille/List.cshtml
@model List<Famille>

<div class="page-header">
    <h3 class="page-title">Listes des Familles</h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/Famille/Ajouter">Ajouter Famille</a></li>
           
        </ol>
    </nav>
</div>
<div class="row">
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <div class="table-responsive">
                    <p>
                        <a class="btn btn-primary btn-rounded btn-icon" asp-action="Ajouter" asp-controller="Famille">
                            <i class="mdi mdi-tag-multiple"></i>
                    </a>
                    </p>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Id Famille</th>
                            <th>Libelle Famille</th>
                            <th>Couleur Associée</th>
                           
                          
                        </tr>
                        @foreach (Famille fm in Model)
                        {
                       <tr>
                                <td>@fm.Id</td>
                                <td>@fm.Libelle</td>
                                <td style="background-color:@fm.Couleur">&nbsp</td>
                           <td>
                                    <center>
                                            <a href="/Famille/Modifier/@fm.Id" class="text-success">
                                                <i class="mdi mdi-table-edit
"></i>
                                            </a> |
                                            <a href="/Famille/Supprimer/@fm.Id" onclick="return confirm('Voulez-Vous Supprimer?');" class="text-danger"><i class="mdi mdi-delete"></i></a>
                                    </center>
                                    </td>
                            </tr>
                        }
                    </thead>
                      
                </table>

                  
</div>
</div>
</div>
</div>
</div>

PFA-Project/Views/Famille/Modifier.cshtml
@model Famille

<div class="page-header">
    <h3 class="page-title">Modification des Familles</h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/Famille/List">Retourner vers la liste</a></li>

        </ol>
    </nav>
</div>
<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">


                <form class="forms-sample" method="post">
                    <div asp-validation-summary="All" />
                    <input type="hidden" asp-for="Id" />
                    <div class="form-group">
                        <label for="ref">Libellé</label>
                        <input type="text" class="form-control" asp-for="Libelle" placeholder="Libellé" />
                        <span asp-validation-for="Libelle"></span>
                    </div>
                    <div class="form-group">
                        <label for="couleur">Couleur</label>
                        <input type="color" class="form-control" asp-for="Couleur" placeholder="Couleur" />
                        <span asp-validation-for="Couleur"></span>
                    </div>
                  
                    <div class="template-demo mt-2">
                        <button type="submit" class="btn btn-outline-primary btn-icon-text">
                            <i class="mdi mdi-file-check btn-icon-prepend"></i> Modifier
                        </button>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>