PFA-Project/Models/Categorie.cs
using System.ComponentModel.DataAnnotations;

namespace PFA_Project.Models
{
    public class Categorie
    {
        [Key]
        public int IdCategorie { get; set; }
        public string? LibelleCategorie { get; set; }
        public List<Article> ?Articles { get; set; }
    }
}

PFA-Project/Controllers/CategorieController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PFA_Project.Filters;
using PFA_Project.Models;

namespace PFA_Project.Controllers
{
    [AuthFilter("Admin")]
    public class CategorieController : Controller
    {
        public ApplicationContext db;
        public CategorieController(ApplicationContext db)
        {
            this.db = db;
        }
        public IActionResult ListCategorie()
        {
            List<Categorie> categories = db.Categories.ToList();
            return View(categories);
        }
        public IActionResult CreateCategorie()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateCategorie(Categorie categorie)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(categorie);
                db.SaveChanges();
                return RedirectToAction("ListCategorie");
            }
            return View(categorie);

        }
        public IActionResult DeleteCategorie(int? id)
        {

            if (id == null)
            {
                return RedirectToAction("ListCategorie");
            }
            var cat = db.Categories.Find(id);
            if (cat != null)
            {
                db.Categories.Remove(cat);
                db.SaveChanges();
                return RedirectToAction("ListCategorie");
            }
            return RedirectToAction("ListCategorie");
        }
        public IActionResult EditCategorie(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("ListCategorie");
            }
            var cat = db.Categories.Find(id);
            if (cat == null)
            {
                return RedirectToAction("ListCategorie");
            }
            return View(cat);
        }
        [HttpPost]
        public IActionResult EditCategorie(Categorie categorie)
        {
            if (ModelState.IsValid)
            {
                db.Update(categorie);
                db.SaveChanges();
                return RedirectToAction("ListCategorie");
            }
            return View(categorie);
        }
    }

}

PFA-Project/Views/Categorie/CreateCategorie.cshtml
@model Categorie

<div class="page-header">
    <h3 class="page-title">Ajouter  des Categories</h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/Categorie/ListCategorie">Retourner vers la liste</a></li>

        </ol>
    </nav>
</div>
<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">


                <form class="forms-sample" method="post">
                     <div asp-validation-summary="All"/>
                    <div class="form-group">
                        <label for="ref">Libelle</label>
                        <input type="text" class="form-control" asp-for="LibelleCategorie" placeholder="LibelleCategorie" />
                        <span asp-validation-for="LibelleCategorie"></span>
                    </div>
                    <div class="template-demo mt-2">
                        <button type="submit" class="btn btn-primary btn-rounded btn-fw"> Ajouter une Categorie</button>

                    </div>
                  
                </form>

            </div>
        </div>
    </div>
</div>

PFA-Project/Views/Categorie/EditCategorie.cshtml
@model Categorie

<div class="page-header">
    <h3 class="page-title">Modification des Categories</h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/Categorie/CreateCategorie">Ajouter</a></li>

        </ol>
    </nav>
</div>
<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">


                    <div class="table-responsive">
                        <table class="table table-dark">
                            <thead>
                                   <form class="forms-sample" method="post">
                    <div asp-validation-summary="All" />
                    <input type="hidden" asp-for="IdCategorie" />
                    <div class="form-group">
                        <label for="ref">Libelle Categorie</label>
                                        <input type="text" class="form-control" asp-for="LibelleCategorie" placeholder="LibelleCategorie" />
                                        <span asp-validation-for="LibelleCategorie"></span>
                    </div>
                                    <div class="template-demo mt-2">
                                        <button type="submit" class="btn btn-outline-primary btn-icon-text">
                                            <i class="mdi mdi-file-check btn-icon-prepend"></i> Modifier Categorie
                                        </button>
                                    </div>
                                </form>

                    </div>
                </div>
            </div>
        </div>

PFA-Project/Views/Categorie/ListCategorie.cshtml
@model List<Categorie>

<div class="page-header">
    <h3 class="page-title">Listes des Catégories</h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/Categorie/CreateCategorie">Ajouter une Catégorie</a></li>

        </ol>
    </nav>
</div>
<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <p>
                        <a class="btn btn-primary btn-rounded btn-icon" asp-action="CreateCategorie" asp-controller="Categorie">
                            <i class="mdi mdi-shape-square-plus"></i>
                        </a>
                    </p>

                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Id Categorie</th>
                                <th>Libelle Categorie</th>
                                <th>Actions</th>
                            </tr>
                            @foreach (Categorie ct in Model)
                            {
                             <tr>
                                    <td>@ct.IdCategorie</td>
                                    <td>@ct.LibelleCategorie</td>
                                   
                                    <td> 
                                        <center>
                                            <a href="/Categorie/EditCategorie/@ct.IdCategorie" class="text-success">
                                                <i class="mdi mdi-table-edit
"></i>
                                            </a> |
                                    <a href="/Categorie/DeleteCategorie/@ct.IdCategorie" onclick="return confirm('Voulez-Vous Supprimer?');" class="text-danger"><i class="mdi mdi-delete"></i></a>
                                        </center>
                                    </td>
                                </tr>
                            }
                        </thead>

                    </table>


                </div>
            </div>
        </div>
    </div>
</div>