PFA-Project/Models/Fournisseur.cs
namespace PFA_Project.Models
{
    public class Fournisseur
    {
        public int Id { get; set; }
        public string ?Nom { get; set; }
        public string ?Adresse { get; set; }
        public string ?N_Tel { get; set; }
        public string ?Email { get; set; }
        public Boolean Statut { get; set; }
        public List<Fourniture> ?Fournitures { get; set; }
    }
}

PFA-Project/Controllers/FournisseurController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PFA_Project.Filters;
using PFA_Project.Models;

namespace PFA_Project.Controllers
{
    [AuthFilter("Admin")]
    public class FournisseurController : Controller
    {
        public ApplicationContext db;
        public FournisseurController(ApplicationContext db)
        {
            this.db = db;
        }
        public IActionResult List()
        {
            List<Fournisseur> fournisseurs = db.Fournisseurs.ToList();
            return View(fournisseurs);
        }
        public IActionResult Ajouter()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Ajouter(Fournisseur fournisseur)
        {
            if (ModelState.IsValid)
            {
                db.Fournisseurs.Add(fournisseur);
                db.SaveChanges();
            }
            return RedirectToAction("List");
        }
        public IActionResult Modifier(int? id)
        {
            var fo = db.Fournisseurs.Find(id);
            if (id == null|| fo == null)
            {
                return RedirectToAction("List");
            }
            return View(fo);
        }
        [HttpPost]
        public IActionResult Modifier(Fournisseur fournisseur)
        {
            if (ModelState.IsValid)
            {
                db.Update(fournisseur);
                db.SaveChanges();
                
            }
            return RedirectToAction("List");

        }
        public IActionResult Supprimer(int? id)
        {
            var fournisseur = db.Fournisseurs.Find(id);
            if (fournisseur != null)
            {
                db.Fournisseurs.Remove(fournisseur);
                db.SaveChanges();
            }
            return RedirectToAction("List");
        }
    }
}

PFA-Project/Views/Fournisseur/Ajouter.cshtml
@model Fournisseur
<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">
                    Ajouter un fournisseur
                </h4>

                <form class="forms-sample" method="post">
                    <div asp-validation-summary="All" />
                    <div class="form-group">
                        <label for="ref">Nom</label>
                        <input type="text" class="form-control" asp-for="Nom" placeholder="Libelle" />
                        <span asp-validation-for="Nom"></span>
                    </div>
                    <div class="form-group">
                        <label for="ref">Adresse</label>
                        <input class="form-control" asp-for="Adresse">
                        <span asp-validation-for="Adresse"></span>
                    </div>
                    <div class="form-group">
                        <label for="ref">Nº Telephone</label>
                        <input class="form-control" asp-for="N_Tel">
                        <span asp-validation-for="N_Tel"></span>
                    </div>
                    <div class="form-group">
                        <label for="ref">Email</label>
                        <input class="form-control" asp-for="Email">
                        <span asp-validation-for="Email"></span>
                    </div>
                    <div class="form-group">
                        <label for="ref">Statut</label>
                        <input type="checkbox" class="form-control" asp-for="Statut">Disponible
                        <span asp-validation-for="Statut"></span>
                    </div>
                    <div class="template-demo mt-2">
                        <button type="submit" class="btn btn-outline-primary btn-icon-text">
                            <i class="mdi mdi-file-check btn-icon-prepend"></i> Ajouter
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

PFA-Project/Views/Fournisseur/List.cshtml
@model List<Fournisseur>
<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <p>
                        <a class="btn btn-primary btn-rounded btn-icon" asp-action="Ajouter" asp-controller="Fournisseur">
                            <i class="mdi mdi-comment-account"></i>
                        </a>
                    </p>
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Id Fournisseur</th>
                                <th>Nom</th>
                                <th>Adresse</th>
                                <th>Nº Telephone</th>
                                <th>Email</th>
                                <th>Statut</th>
                                <th>Actions</th>
                            </tr>
                            @foreach (Fournisseur fournisseur in Model)
                            {
                                <tr>
                                    <td>@fournisseur.Id</td>
                                    <td>@fournisseur.Nom</td>
                                    <td>@fournisseur.Adresse</td>
                                    <td>@fournisseur.N_Tel</td>
                                    <td>@fournisseur.Email</td>
                                    <td>@fournisseur.Statut</td>
                                    <td>
                                        <center>
                                            <a href="/Fournisseur/Modifier/@fournisseur.Id" class="text-success">
                                                <i class="mdi mdi-table-edit"></i>
                                            </a> |
                                            <a href="/Fournisseur/Supprimer/@fournisseur.Id" onclick="return confirm('Voulez-Vous Supprimer?');" class="text-danger"><i class="mdi mdi-delete"></i></a>
                                        </center>
                                    </td>
                                    </tr>
                            }
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

PFA-Project/Views/Fournisseur/Modifier.cshtml
@model Fournisseur

<div class="page-header">
    <h3 class="page-title">Modification des fournisseurs</h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/Fournisseur/List">Retourner vers la liste</a></li>

        </ol>
    </nav>
</div>
<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">


                <form class="forms-sample" method="post">
                    <div asp-validation-summary="All" />
                    <input type="hidden" asp-for="Id" />
                    <div class="form-group">
                        <label for="ref">Libellé</label>
                        <input type="text" class="form-control" asp-for="Nom" placeholder="Nom" />
                        <span asp-validation-for="Nom"></span>
                    </div>
                    <div class="form-group">
                        <label for="ref">Adresse</label>
                        <input type="text" class="form-control" asp-for="Adresse" placeholder="Adresse" />
                        <span asp-validation-for="Adresse"></span>
                    </div>

                    <div class="form-group">
                        <label for="ref">Nº Telephone</label>
                        <input type="text" class="form-control" asp-for="N_Tel" placeholder="Nº Telaphone" />
                        <span asp-validation-for="N_Tel"></span>
                    </div>
                    <div class="form-group">
                        <label for="ref">Email</label>
                        <input type="text" class="form-control" asp-for="Email" placeholder="Email" />
                        <span asp-validation-for="Email"></span>
                    </div>
                    <div class="form-group">
                        <label for="ref">Statut</label>
                        <input class="form-control" asp-for="Statut"/>
                        <span asp-validation-for="Statut"></span>
                    </div>
                    <div class="template-demo mt-2">
                        <button type="submit" class="btn btn-outline-primary btn-icon-text">
                            <i class="mdi mdi-file-check btn-icon-prepend"></i> Modifier
                        </button>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>